### ISSUE TITLE
Simulate Sauce Runner in Rpi

### ISSUE THREAD

**Issue by johsecaba** [open-kitchen/open-kitchen#22]
**The following information is found on Hardware Project Description file.** 

The Sauce runner is one of the components of the Sauce-Dispenser Module (SDM) description. 

The following is how the SDM subsystems is composed: 

- Sauce Loading Station: sauce supply station, filled up by staff

- **Sauce runner:** Autonomous sauce apparatus use as the sauce dispenser

- Horizontal rail system: Apparatus that transports the sauce runner through the various wok-modules and which contains a hose system which allows for uninterrupted supply of sauces from the sauce loading station

- [ ] The simulation should portrait the continuous function/relationship between the Sauce Loading Station (continuously feed the sauce runner) and the Sauce runner. 

- [ ] This simulation should easily be able to turn into a control interface of the Sauce-dispenser Module (SDM) unit. 

- [x] The runner should be able to move from it’s base to a wok and release the sauces needed

- [ ] The simulation should portrait a runner that can continuously feed multiple woks without need to refill on loading station. The SDM was designed to feed sauce continually to the runner.  

- [x] The runner should notify when it releases the sauce and when it’s done

- [x] The runner should stop work when the loading station gives low level signal to allow for staff to refill 

Keep in mind that the sauce runner makes part of the Sauce-dispenser Module (SDM) and the Wok units are part of the Cooking Assembly (CA). Both, the sauce runner and the wok units have to be synced in order for them to work accurately. 

**The description on how the sauce runner operates is on file "Hardware Project Description". Please read before start of work.** 

![image](https://user-images.githubusercontent.com/50690729/72658151-fc4e3a80-397a-11ea-876f-b811b39a022c.png)

**Comment by johsecaba** [comment]
Use Case Diagram for CA & SDM
https://drive.google.com/file/d/1gi441S0rdDmoMpltW_SjQEiHTKVe0amk/view?usp=sharing

SysML Overview - Check **Packet 3**
https://docs.google.com/document/d/1iwhwVnhnsCMLz9Yjz2TOwjHziYGx6PEE2KF3bQehvlc/edit?usp=sharing

**Comment by NunchakusLei** [comment]
The work is merged to `development` branch.
